
const projects=window.PORTFOLIO_DATA;
const heroImgs=[...document.querySelectorAll('.hero-img')];let heroIndex=0;
function showHero(i){heroIndex=(i+heroImgs.length)%heroImgs.length;heroImgs.forEach((x,n)=>x.classList.toggle('active',n===heroIndex))}
showHero(0);document.getElementById('heroNext').addEventListener('click',()=>showHero(heroIndex+1));
let timer=setInterval(()=>showHero(heroIndex+1),5200);document.querySelector('.hero-frame').addEventListener('mouseenter',()=>clearInterval(timer));
const projectView=document.getElementById('projectView'),projectHeading=document.getElementById('projectHeading'),projectCopy=document.getElementById('projectCopy'),projectGallery=document.getElementById('projectGallery');
function openProject(key){const p=projects[key];if(!p)return;projectHeading.textContent=p.title;projectCopy.innerHTML=`<h2>${p.title}</h2><div><p class="jp">${p.jp}</p><p>${p.desc}</p><p>${String(p.files.length).padStart(2,'0')} photographs</p></div>`;projectGallery.innerHTML=p.files.map((f,i)=>`<figure class="project-photo" data-lightbox="images/${f}"><img src="images/${f}" loading="lazy" decoding="async" alt="${p.jp} ${i+1}"></figure>`).join('');projectView.classList.add('open');projectView.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';projectView.scrollTop=0;bindLightbox(projectGallery);history.replaceState(null,'',`#${key}`)}
function closeProject(){projectView.classList.remove('open');projectView.setAttribute('aria-hidden','true');document.body.style.overflow='';history.replaceState(null,'','#works')}
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project)));document.getElementById('projectClose').addEventListener('click',closeProject);document.getElementById('projectCloseBottom').addEventListener('click',closeProject);
const lightbox=document.getElementById('lightbox'),lightboxImg=document.getElementById('lightboxImg');function openLightbox(src){lightboxImg.src=src;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false')}function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');lightboxImg.src=''}
function bindLightbox(root=document){root.querySelectorAll('[data-lightbox]').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound='1';el.addEventListener('click',e=>{e.stopPropagation();openLightbox(el.dataset.lightbox)})})}bindLightbox();document.getElementById('lightboxClose').addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(lightbox.classList.contains('open'))closeLightbox();else if(projectView.classList.contains('open'))closeProject()}});
if(location.hash && projects[location.hash.slice(1)]) openProject(location.hash.slice(1));
